baseURL         = "https://rms1000watt.com"
title           = "rms1000watt"
theme           = "liva-hugo"
publishDir      = "../public"
languageCode    = "en-us"
summaryLength   = "10"
paginate        = 6
disqusShortname = ""
pygmentsUseClasses = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.plugins]

  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

[menu]

  # [[menu.main]]
  # name   = "About"
  # URL    = "about"
  # weight = 1

  [[menu.main]]
  name   = "Blog"
  URL    = "blog"
  weight = 2

  [[menu.main]]
  name   = "Contact"
  URL    = "contact"
  weight = 3

  # [[menu.footer]]
  # name   = "About"
  # URL    = "about"
  # weight = 1

  [[menu.footer]]
  name   = "Blog"
  URL    = "blog"
  weight = 2

  [[menu.footer]]
  name   = "Contact"
  URL    = "contact"
  weight = 3

[params]
logo        = "images/logo-35.png"
home        = "Home"
description = "This is meta description"
author      = "Ryan Smith"
mobile      = "949-232-0216"
email       = "rms1000watt@gmail.com"
location    = "Irvine, CA"
copyright   = "| copyright &copy; 2020 Ryan Smith |"

googleAnalitycsID = "Your ID"

  [params.preloader]
  enable    = true
  preloader = "" # use .png , .svg or .gif format

  [params.search]
  enable = true

  [params.newsletter]
  # TODO: enable true later
  enable = false
  title = "Stay in Touch"
  content = "If you'd like to stay up to date with new posts here, please share your email address to recieve updates on new content!"

  [[params.social]]
  title = "twitter"
  icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
  link = "https://twitter.com/rms1000watt"

  [[params.social]]
  title = "github"
  icon = "ti-github"
  link = "https://github.com/rms1000watt"

  [[params.social]]
  title = "linkedin"
  icon = "ti-linkedin"
  link = "https://linkedin.com/in/ryanmatthewsmith"